// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: v2/concordium/health.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthClient interface {
	// Check the health of the node. By necessity this involves a number of
	// heuristics since in a distributed network we have to rely on the local
	// information only and we don't have authoritative data on, e.g., last
	// finalized block.
	//
	// In particular, a node that is not caught up to the head of the chain is not
	// healthy.
	//
	// If possible the client should use other queries to get a more fine-grained
	// understanding of the node health. However this endpoint should provide a
	// reasonable default and is usable in cases where an automatic check is
	// performed that does not allow for configuration, such as in load-balancers.
	Check(ctx context.Context, in *NodeHealthRequest, opts ...grpc.CallOption) (*NodeHealthResponse, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *NodeHealthRequest, opts ...grpc.CallOption) (*NodeHealthResponse, error) {
	out := new(NodeHealthResponse)
	err := c.cc.Invoke(ctx, "/concordium.health.Health/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility
type HealthServer interface {
	// Check the health of the node. By necessity this involves a number of
	// heuristics since in a distributed network we have to rely on the local
	// information only and we don't have authoritative data on, e.g., last
	// finalized block.
	//
	// In particular, a node that is not caught up to the head of the chain is not
	// healthy.
	//
	// If possible the client should use other queries to get a more fine-grained
	// understanding of the node health. However this endpoint should provide a
	// reasonable default and is usable in cases where an automatic check is
	// performed that does not allow for configuration, such as in load-balancers.
	Check(context.Context, *NodeHealthRequest) (*NodeHealthResponse, error)
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have forward compatible implementations.
type UnimplementedHealthServer struct {
}

func (UnimplementedHealthServer) Check(context.Context, *NodeHealthRequest) (*NodeHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concordium.health.Health/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*NodeHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "concordium.health.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/concordium/health.proto",
}
